### ISSUE TITLE
Can we omit parentheses for methods without arguments?

### ISSUE THREAD

**Issue by aerni** [Stillat/primitives#5]
I'm using this package for [aerni/statamic-factory](https://github.com/aerni/statamic-factory). Factory let's users define faker formatters in their blueprint. You can define simple formatters like this `lastName`. Only formatters with arguments require the parentheses like `numberBetween(20, 50)`.

**Example Blueprint:**
```yaml
-
  handle: last_name
  field:
    type: text
    factory: lastName
-
  handle: age
  field:
    type: number
    factory: numberBetween(20, 50)
```

To handle this, I'm using the following logic. I was wondering if there was a way to make this parser pick up on the missing `()` or if the below code makes sense.

```php
/**
* Handle Faker formatters with arguments.
*/
if (Str::containsAll($fakerFormatter, ['(', ')'])) {
    return $this->runner->run(
        $this->parser->parseMethods($fakerFormatter),
        $this->faker
    );
}

/**
* Handle simple Faker formatters.
*/
return $this->faker->$fakerFormatter();
```
